### PR TITLE
chore: migrate to monorepo

### PR DESCRIPTION
**Pull request by baseballyama**
WIP. Still there are a lot of todos.
-> I will continue work on next weekend. (18th, 19th May)

### CODE REVIEW

**Comment by baseballyama** [comment]
@ota-meshi 

I realized that currently we can not support ESLint v9.3.0 in docs project. (Not eslint-plugin-svelte itself.)

We need to fix [vite-plugin-eslint4b](https://github.com/ota-meshi/vite-plugin-eslint4b), so I created a PR.

https://github.com/ota-meshi/vite-plugin-eslint4b/pull/51

**Comment by baseballyama** [comment]
@ota-meshi Almost done but https://github.com/ota-meshi/vite-plugin-eslint4b/pull/51 and https://github.com/ota-meshi/vite-plugin-eslint4b/pull/53 are blocker.
I will do self-review for this but I don't have confident that changeset release works properly or not😅

**Comment by baseballyama** [comment]
@ota-meshi 

I need your help!
Still I can not build docs project due to file path mismatch.

https://github.com/sveltejs/eslint-plugin-svelte/assets/19153718/becd51d0-1a56-49d3-be79-7a54d6d72dd9

I think https://github.com/ota-meshi/vite-plugin-eslint4b/pull/55 breaks this. But I'm not sure how to solve the issue. Maybe we can revert I think https://github.com/ota-meshi/vite-plugin-eslint4b/pull/55 or you have better idea.

**Comment by ota-meshi** [comment]
> I think https://github.com/ota-meshi/vite-plugin-eslint4b/pull/55 breaks this.

Hmm... It was a [CI error] so I made some changes.  I will check out this branch later and give it a try.

[CI error]: https://github.com/ota-meshi/vite-plugin-eslint4b/actions/runs/9219962911

**Comment by ota-meshi** [comment]
I fixed `vite-plugin-eslint4b` and I think the `build` script is passing. However, the playground launched by the `dev` script still doesn't work. I don't know what the difference is yet.

**Comment by baseballyama** [comment]
@ota-meshi

Thank you for fixing this!
As far as I know, the dev command is not working properly on the main branch either.
So I think we can merge this PR after completing the following tasks:

- Ensuring that the release process is not broken (since CI cannot check this, we need to verify it manually)
- Conducting a general code review

**Comment by baseballyama** [comment]
This is not related to this PR, but do you think it is possible to convert the documentation project to ESM?
There are plans to consolidate Svelte-related documentation into a single omnisite, which will need to be migrated to ESM before this can be done.

**Comment by ota-meshi** [comment]
> This is not related to this PR, but do you think it is possible to convert the documentation project to ESM?

Yes, I believe we can migrate our documentation to the ESM project.

**Review by ota-meshi — APPROVED** [review]
Awesome! Thank you for doing a great job!

**Comment by baseballyama** [comment]
Hum...

image

**Comment by baseballyama** [comment]
I'm fixing.

**Comment by baseballyama** [comment]
Fixed: https://github.com/sveltejs/eslint-plugin-svelte/actions/runs/9427331361/job/25971325775

**Comment by baseballyama** [comment]
And I confirmed that the site is working properly.

**Pull request merged**
