### PR TITLE
feat: Added the `no-unused-class-name` rule

### PR DESCRIPTION
**Pull request by marekdedic**

### CODE REVIEW

**Comment by marekdedic** [comment]
Well, this is going to be interesting... :D 
@ota-meshi if I understand it correctly, `svelte-eslint-parser` doesn't actually parse the styles - `SvelteStyleElement.children` is just a `SvelteText` with the raw CSS - this isn't gonna be enough for this rule. Any plans to parse the CSS the same way as JS in `svelte-eslint-parser`? (And yes, it's going to need to support languages like SCSS and preprocessors as well - like it supports TS).

**Comment by ota-meshi** [comment]
I currently have no plans to allow `svelte-eslint-parser` to parse `<style>`. Converting many CSS flavors into an AST that ESLint understands is difficult.

To implement the `no-unused-class-name` rule, I think we need to extract the CSS of the `<style>` tag and parse it with [postcss]. Next, I think it is necessary to extract the selector from the `postcss` AST and parse it with [postcss-selector-parser].

[postcss]: https://www.npmjs.com/package/postcss
[postcss-selector-parser]: https://www.npmjs.com/package/postcss-selector-parser

If you want to support CSS preprocessors, please refer to the code around the following link.
https://github.com/ota-meshi/eslint-plugin-svelte/blob/09b01ad1ce208c6dbbf8357914d3aadb71c57a4e/src/shared/svelte-compile-warns/index.ts#L24

**Comment by baseballyama** [comment]
Why do we need this rule?
Already Svelte compiler itself has this feature.

**Comment by ota-meshi** [comment]
The purpose of this rule is to detect classes specified on elements that were not used in CSS. #401.
It does not detect unused selectors (classes) in CSS.
I think this rule can be useful if your project doesn't use classes outside of `*.svelte` CSS.

**Comment by baseballyama** [comment]
Got it!

**Comment by marekdedic** [comment]
Waiting for sveltejs/svelte-eslint-parser#318

**Comment by marekdedic** [comment]
Obsoleted by #489

**Pull request closed without merging**
