### PR TITLE
feat!: drop support for old node versions (<18, 19, 21)

### PR DESCRIPTION
**Pull request by ota-meshi**

### CODE REVIEW

**Comment by baseballyama** [comment]
Do we want to drop ESLint v8 also?😀 (At least v7?)

**Comment by ota-meshi** [comment]
I would like to change to only supporting ESLint latest and v8.57.1. I want to keep v8.57.1 ​​to make it easier for users to migrate, but I'm not that strict about it. I'm okay to drop support v8.57.1.

**Comment by baseballyama** [comment]
Question: Do we need to drop ESLint v8.57.1 if we want ESM only?

**Comment by ota-meshi** [comment]
ESLint v8.57.1 ​​also has an (experimental) Flat Config available, so I don't think it will block us from changing it to ESM.

**Comment by baseballyama** [comment]
OK! So I agreed that we will support only ESLint v8.57.1 and v9 in next major version.

**Review by baseballyama — APPROVED** [review]

**Pull request merged**
